/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.ac.uryukyu.ie.e235221;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class EnemyTest {
	@Test
	void attackTest() {
		int defaultHeroHp = 100;
		Hero demoHero = new Hero("デモ勇者", defaultHeroHp, 100);
		Enemy slime = new Enemy("スライムもどき", 10, 100);

		for (int count = 0; count < 10; count++) {
			demoHero.attack(slime); // over kill
		}

		slime.attack(demoHero);
		assertEquals(defaultHeroHp, demoHero.getHitPoint());
	}

	@Test
	public void testAttackAfterDeath() {
		Hero hero = new Hero("勇者", 10, 5);
		Enemy enemy = new Enemy("スライム", 6, 3);

		enemy.attack(hero);
		enemy.attack(hero);
		enemy.attack(hero);
		enemy.attack(hero); // ここでenemyは死亡しているはず

		assertTrue(enemy.isDead());
		assertEquals(10, hero.getHitPoint()); // heroのHPは変わらないはず
	}
}
